[package]
name = "solana-accountsdb-sqs"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.44"
arrayref = "0.3.6"
async-trait = "0.1"
base64 = "0.13.0"
clap = "2.34.0"
humantime = "2.1.0"
log = "0.4.14"
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_sqs = "0.47"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
solana-accountsdb-plugin-interface = "=1.8.14"
solana-logger = "=1.8.14"
solana-sdk = "=1.8.14"
spl-token = "3.2.0"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "time", "macros"] }

[profile.release]
lto = true
codegen-units = 1
